server:
  port: 8083

spring:
  application:
    name: emp-provider
  datasource: #配置数据源信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empmanager?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true #控制台是否打印sql
    generate-ddl: true #配置正向工程(通过实体类产生数据库表)
    hibernate: #在启动项目的时候根据实体类生成数据库表,如果不一致更新表
      ddl-auto: update
    #配置数据库方言，jpa开发的java程序可以实现跨数据库平台
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
                       #org.hibernate.dialect.MySQL5Dialect
                       #org.hibernate.dialect.MySQL5InnoDBDialect
#配置注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


